/**
 * Backfill salonLat, salonLng, locationZip for Professionals with salonAddress but no coordinates.
 *
 * Uses Nominatim (free, no API key). Rate limit: 1 req/sec.
 *
 * Prerequisites:
 * - npx ampx sandbox (or deployed backend) running
 * - amplify_outputs.json present (generated by sandbox)
 *
 * Run: node scripts/backfillProfessionalGeocoding.js
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import { geocodeAddressWithRateLimit } from '../src/utils/geocoding.js';
import { extractZipFromLocation } from '../src/matching/matchingEngine.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load and configure Amplify
try {
  const outputsPath = join(__dirname, '../amplify_outputs.json');
  const outputs = JSON.parse(readFileSync(outputsPath, 'utf8'));
  Amplify.configure(outputs);
} catch (err) {
  console.error('Failed to load amplify_outputs.json. Run: npx ampx sandbox');
  console.error(err.message);
  process.exit(1);
}

async function main() {
  let client;
  try {
    client = generateClient();
  } catch (err) {
    console.error('Failed to initialize Amplify client:', err.message);
    process.exit(1);
  }

  console.log('Fetching professionals with salonAddress but missing salonLat/salonLng...\n');

  let professionals = [];
  try {
    const { data } = await client.models.Professional.list({});
    professionals = (data || []).filter(
      (p) =>
        p.salonAddress &&
        p.salonAddress.trim().length > 0 &&
        (p.salonLat == null || p.salonLng == null)
    );
  } catch (err) {
    console.error('Failed to list professionals:', err.message);
    process.exit(1);
  }

  if (professionals.length === 0) {
    console.log('No professionals need geocoding. All done.');
    return;
  }

  console.log(`Found ${professionals.length} professional(s) to geocode.\n`);

  let updated = 0;
  let failed = 0;

  for (const pro of professionals) {
    const addr = pro.salonAddress.trim();
    console.log(`Geocoding: ${pro.firstName} ${pro.lastName} - ${addr}`);

    try {
      const coords = await geocodeAddressWithRateLimit(addr);
      if (!coords) {
        console.log(`  ❌ Geocode failed: ${addr}`);
        failed++;
        continue;
      }

      const locationZip = extractZipFromLocation(addr) || null;

      await client.models.Professional.update({
        id: pro.id,
        salonLat: coords.lat,
        salonLng: coords.lng,
        locationZip,
      });

      console.log(`  ✅ Updated: lat=${coords.lat.toFixed(4)}, lng=${coords.lng.toFixed(4)}, zip=${locationZip || 'n/a'}`);
      updated++;
    } catch (err) {
      console.log(`  ❌ Error: ${err.message}`);
      failed++;
    }
  }

  console.log(`\nDone. Updated: ${updated}, Failed: ${failed}`);
}

main().catch((err) => {
  console.error('Script error:', err);
  process.exit(1);
});
