export const waitlistStyles = {
  container: {
    minHeight: '100vh',
    background: '#FFFEF9',
    color: '#4A2A1A',
    fontFamily: '"Alike", "Georgia", serif',
    padding: '1rem',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    maxWidth: '600px',
    margin: '0 auto 1.5rem',
  },
  backBtn: {
    padding: '0.5rem 1rem',
    fontSize: '0.9rem',
    cursor: 'pointer',
    borderRadius: '25px',
    border: '1px solid rgba(139, 30, 63, 0.2)',
    backgroundColor: 'transparent',
    color: '#4A2A1A',
    fontFamily: '"Alike", "Georgia", serif',
  },
  logo: {
    fontSize: '1.5rem',
    fontWeight: '700',
    letterSpacing: '0.1em',
    color: '#8B1E3F',
    fontFamily: '"Alike", "Georgia", serif',
  },
  formContainer: {
    maxWidth: '560px',
    margin: '0 auto',
    background: '#FFFEF9',
    borderRadius: '20px',
    padding: '2rem',
    border: '1px solid rgba(139, 30, 63, 0.15)',
    boxShadow: '0 4px 20px rgba(139, 30, 63, 0.08)',
  },
  title: {
    fontSize: '1.75rem',
    textAlign: 'center',
    marginBottom: '0.5rem',
    color: '#4A2A1A',
    fontFamily: '"Alike", "Georgia", serif',
  },
  subtitle: {
    textAlign: 'center',
    color: '#5A3A2A',
    marginBottom: '2rem',
    fontSize: '0.95rem',
    fontFamily: '"Alike", "Georgia", serif',
    lineHeight: 1.5,
  },
  formGroup: { marginBottom: '1.25rem' },
  label: {
    display: 'block',
    marginBottom: '0.4rem',
    fontSize: '0.95rem',
    color: '#4A2A1A',
    fontFamily: '"Alike", "Georgia", serif',
  },
  input: {
    width: '100%',
    padding: '0.9rem 1.1rem',
    fontSize: '1rem',
    borderRadius: '12px',
    border: '2px solid rgba(139, 30, 63, 0.2)',
    backgroundColor: '#FFFEF9',
    color: '#4A2A1A',
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: '"Alike", "Georgia", serif',
  },
  select: {
    width: '100%',
    padding: '0.9rem 1.1rem',
    fontSize: '1rem',
    borderRadius: '12px',
    border: '2px solid rgba(139, 30, 63, 0.2)',
    backgroundColor: '#FFFEF9',
    color: '#4A2A1A',
    cursor: 'pointer',
    fontFamily: '"Alike", "Georgia", serif',
  },
  textarea: {
    width: '100%',
    padding: '0.9rem 1.1rem',
    fontSize: '1rem',
    borderRadius: '12px',
    border: '2px solid rgba(139, 30, 63, 0.2)',
    backgroundColor: '#FFFEF9',
    color: '#4A2A1A',
    outline: 'none',
    boxSizing: 'border-box',
    minHeight: '100px',
    resize: 'vertical',
    fontFamily: '"Alike", "Georgia", serif',
  },
  primaryBtn: {
    width: '100%',
    padding: '1rem',
    fontSize: '1rem',
    cursor: 'pointer',
    borderRadius: '10px',
    border: 'none',
    background: 'linear-gradient(135deg, #8B1E3F, #A85A5A)',
    color: '#FFFEF9',
    fontWeight: '600',
    fontFamily: '"Alike", "Georgia", serif',
    marginTop: '0.5rem',
  },
  hint: {
    fontSize: '0.8rem',
    color: '#5A3A2A',
    marginTop: '0.35rem',
    opacity: 0.85,
  },
};
